### ISSUE TITLE
不兼容

### ISSUE THREAD

**Issue by 466aijq** [fei-ke/HMSPush#1]
安卓pie安装不了

**Comment by duzhaokun123** [comment]
minsdk 29

就没打算让 Android 9 用

**Comment by fei-ke** [comment]
Android 9 可以支持，我晚点打个包可以试一下

**Comment by fei-ke** [comment]
https://github.com/fei-ke/HMSPush/actions/runs/2758869755

**Comment by 466aijq** [comment]
> https://github.com/fei-ke/HMSPush/actions/runs/2758869755
> @466aijq 可以试一下这个包

好的，谢谢

**Comment by 466aijq** [comment]
> minsdk 29
> 
> 就没打算让 Android 9 用

对对对，你安卓12还是13，你清高，别人就不能用pie养老

**Comment by duzhaokun123** [comment]
> > minsdk 29
> > 就没打算让 Android 9 用
> 
> 对对对，你安卓12还是13，你清高，别人就不能用pie养老

你开 issue 时是 2022.7.28 当时最新的 release 是 https://github.com/fei-ke/HMSPush/releases/tag/v0.0.7

这个包的 minsdk 是 29

minsdk 不是我定的 所以不是我不让你用

我只是陈述事实

你应该职责的对象是 @fei-ke

**Comment by 466aijq** [comment]
> > > minsdk 29
> > > 就没打算让 Android 9 用
> > 
> > 对对对，你安卓12还是13，你清高，别人就不能用pie养老
> 
> 你开 issue 时是 2022.7.28 当时最新的 release 是 https://github.com/fei-ke/HMSPush/releases/tag/v0.0.7
> 
> 这个包的 minsdk 是 29
> 
> minsdk 不是我定的 所以不是我不让你用
> 
> 我只是陈述事实
> 
> 你应该指责的对象是 @fei-ke 

不好意思，理解错了，但是作者已经给出解决方案了
