### ISSUE TITLE
可以伪装成支持gms的机型吗？

### ISSUE THREAD

**Issue by ltkun** [fei-ke/HMSPush#10]
装了hmapush 结果谷歌discover流没了
只能暂时卸载了
不过卸载了还是继续推送着...

**Comment by fei-ke** [comment]
不要全局伪装设备机型，只对需要推送的应用伪装就行

**Comment by ltkun** [comment]
> 不要全局伪装设备机型，只对需要推送的应用伪装就行

0.13版刚刚试了 lsposed不勾选的系统框架 hmspush就不起作用
