### ISSUE TITLE
有注册推送记录时间无通知栏推送

### ISSUE THREAD

**Issue by qiuyouxin** [fei-ke/HMSPush#11]
有注册推送记录时间无通知栏推送
问题：例，QQ注册后始终有推送时间记录更新，但无任何通知栏推送，hms core已内置system/app
机型：lg 官方 Android 9.0
（能否把push包名改成官方相关推送组件相同包名，避免被检测到xposed模块。或者说隐藏push模块会不会影响app的注册？）
[LSPosed_2022-08-19T18_19_07.333.zip](https://github.com/fei-ke/HMSPush/files/9381416/LSPosed_2022-08-19T18_19_07.333.zip)

**Comment by fei-ke** [comment]
https://github.com/fei-ke/HMSPush/releases/tag/v0.0.13
Android 9 推送已修复，隐藏push是否影响注册请自行测试
