### ISSUE TITLE
能注册不会推送

### ISSUE THREAD

**Issue by XdpAreKid** [fei-ke/HMSPush#12]
大佬，我这企业微信能注册但是推不了，能帮我看一下吗？？
[LSPosed_2022-08-24T23_40_52.406.zip](https://github.com/fei-ke/HMSPush/files/9417562/LSPosed_2022-08-24T23_40_52.406.zip)

**Comment by XdpAreKid** [comment]
其他的应用有些能推，有些也不能，像支付宝能推，但是饿了么就推不了

**Comment by XdpAreKid** [comment]
- [ ]

**Comment by YimingZhanshen** [comment]
我发现miui会自动清除HMSPush的后台，导致无法收到消息，这点很烦。。。

**Comment by XdpAreKid** [comment]
> 我发现miui会自动清除HMSPush的后台，导致无法收到消息，这点很烦。。。

hmspush在不在后台应该无所谓，主要是hms core
