### ISSUE TITLE
这个可以适配应用图标吗

### ISSUE THREAD

**Issue by mizhihan** [fei-ke/HMSPush#13]
![16614157416858080569499666939859](https://user-images.githubusercontent.com/71163533/186614108-bc55dd11-e87c-4016-9c50-6b1d86acf96e.jpg)
![16614157682737500199283879661964](https://user-images.githubusercontent.com/71163533/186614169-d5a09a6c-f38b-44e9-8157-bfd29f2c38da.jpg)
不然不好分辨是哪个软件的，谢谢。

**Comment by Maplerm** [comment]
安卓机器人看上去太难受了

**Comment by Potat0000** [comment]
同求

**Comment by notxx** [comment]
#18 改进了一下

**Comment by fei-ke** [comment]
https://github.com/fei-ke/HMSPush/actions/runs/3077608265
