### ISSUE TITLE
酷安不推送

### ISSUE THREAD

**Issue by 2581868503** [fei-ke/HMSPush#2]
酷安机型不显示然后没有通知

**Comment by fei-ke** [comment]
上传 lsp 日志

**Comment by 2581868503** [comment]
https://wwi.lanzoup.com/iBVa308phmtc

**Comment by fei-ke** [comment]
@2581868503 试一下这个版本 https://github.com/fei-ke/HMSPush/releases/tag/v0.0.8-alpha2

**Comment by 2581868503** [comment]
这个版本还是不行😂Tim和QQ，网易云都可以正常推送，酷安还是不行，这个版本显示的是用的手机型号而不是华为的型号，也不是上个版本显示空白

**Comment by 2581868503** [comment]
lsp日志
https://wwi.lanzoup.com/ixRGQ08posof

**Comment by fei-ke** [comment]
> lsp日志 https://wwi.lanzoup.com/ixRGQ08posof

看日志推送通道是注册成功的，重新登录，清数据之类的试试吧
