### ISSUE TITLE
哔哩哔哩漫画推送无法注册

### ISSUE THREAD

**Issue by EvatsugDnalloR** [fei-ke/HMSPush#21]
无论重启哔漫多少遍都无法注册，其他的想b站酷安qq都能推送，就只有哔漫无法注册，可以确定的是哔漫包里肯定带华为push服务的...
![Screenshot_20220922-001125_HMS Core.png](https://user-images.githubusercontent.com/86464406/191620070-066f8086-9ff3-4555-8812-e78519354f35.png)
![Screenshot_20220922-001425_Shell.png](https://user-images.githubusercontent.com/86464406/191620082-e709ee83-4a98-45c1-a4a7-860fe8bd2daf.png)
![Screenshot_20220922-001447_LibChecker.png](https://user-images.githubusercontent.com/86464406/191620090-6be95b4e-9140-4126-a5cb-f65b95b0fd2f.png)

**Comment by EvatsugDnalloR** [comment]
忘记说了模块版本0.0.16加上HMS core 6.7.0.320（都是最新版）

**Comment by fei-ke** [comment]
排查 com.bilibili.comic 4.21.0 版本，发现应用未正确接入华为 Push，请向官方反馈

具体为在 AndroidMenifest 中声明 `com.huawei.hms.client.appid` 格式有误：
```xml
<meta-data android:name="com.huawei.hms.client.appid" android:value="appid=xxxx" />
```

正确格式为：
```xml
<meta-data android:name="com.huawei.hms.client.appid" android:value="xxxx" />
```
