### ISSUE TITLE
签名验证开关无法正常打开

### ISSUE THREAD

**Issue by Arlia-Etoile** [fei-ke/HMSPush#27]
最新版模块中的禁用签名验证开关无法打开，模块内切换页面后该开关会自动关闭，且将页面保留也无法生效。

模块版本：0.0.18
系统：one ui 4.1 (Android 12 )
手机型号：SM-G9810(s20)

**Comment by Arlia-Etoile** [comment]
录屏：
https://linksharing.samsungcloud.com/bYQkQwXH951Q

**Comment by fei-ke** [comment]
日志发一下，另外你这是多用户吗

**Comment by Arlia-Etoile** [comment]
是多用户，lspatch（副账户） 里面没有日志，只能是上传lsposed（主账户）里的
[https://linksharing.samsungcloud.com/ndZLEiqZs3TB](url)

**Comment by fei-ke** [comment]
目前不支持多用户
