### ISSUE TITLE
是否考虑适配lspatch

### ISSUE THREAD

**Issue by ZhangCharlie** [fei-ke/HMSPush#3]
测试hmspush在lspatch环境下伪装功能是生效的，但lspatch无法作用于系统框架，无法hook系统通知，能否在无法hook系统的情况下单独运行一个服务专门提供通知功能达到不唤醒应用的目的

**Comment by fei-ke** [comment]
HMS 应该是做了签名校验之类的，lspatch 理论上可行，我抽空看看

**Comment by fei-ke** [comment]
@ZhangCharlie 可以试试这个 https://github.com/fei-ke/HMSPush/actions/runs/2833514979

**Comment by ZhangCharlie** [comment]
> @ZhangCharlie 可以试试这个 https://github.com/fei-ke/HMSPush/actions/runs/2833514979

系统三星s22 oneui4.0,  用的TIM,  lspatch 本地模式， 作用域选hmspush
1. 杀后台后没有收到push通知，再次打开TIM后会立即弹出push通知，TIM自己也会弹一条一模一样的通知（多了头像）
2. 不杀后台的话又不会走push通道

**Comment by fei-ke** [comment]
> > @ZhangCharlie 可以试试这个 https://github.com/fei-ke/HMSPush/actions/runs/2833514979
> 
> 系统三星s22 oneui4.0, 用的TIM, lspatch 本地模式， 作用域选hmspush
> 
> 1. 杀后台后没有收到push通知，再次打开TIM后会立即弹出push通知，TIM自己也会弹一条一模一样的通知（多了头像）
> 2. 不杀后台的话又不会走push通道
> 3. 不杀后台锁屏过一会后，切到前台时又会弹出push通知了
> 
> 大概就是不切到前台，push通知弹不出来， 不知道是不是三星系统原因

HMS Core 给自启权限、后台电池不优化试试

**Comment by ZhangCharlie** [comment]
> > > @ZhangCharlie 可以试试这个 https://github.com/fei-ke/HMSPush/actions/runs/2833514979
> > 
> > 
> > 系统三星s22 oneui4.0, 用的TIM, lspatch 本地模式， 作用域选hmspush
> > 
> > 1. 杀后台后没有收到push通知，再次打开TIM后会立即弹出push通知，TIM自己也会弹一条一模一样的通知（多了头像）
> > 2. 不杀后台的话又不会走push通道
> > 3. 不杀后台锁屏过一会后，切到前台时又会弹出push通知了
> > 
> > 大概就是不切到前台，push通知弹不出来， 不知道是不是三星系统原因
> 
> HMS Core 给自启权限、后台电池不优化试试

HMSCore已经自启并电池不优化了，而且TIM也给了自启

**Comment by ZhangCharlie** [comment]
已经找到lspatch的正确使用方法，就是hmscore也要进行修补，然后推送就正常了，发现一些体验不好的地方，所有应用的通知都折叠为hmscore了，通知也不能单独控制，能否将每个应用各自折叠为一栏，且支持各个应用单独设置通知

**Comment by ZhangCharlie** [comment]
lspatch已经可用
