### ISSUE TITLE
企业微信已注册但是无法推送

### ISSUE THREAD

**Issue by spark-777** [fei-ke/HMSPush#38]
https://wwp.lanzoup.com/iW6HF0ge5u4f这是lsp日志

**Comment by zintine** [comment]
我的企业微信是怎么也不注册

**Comment by fei-ke** [comment]
日志中没有企业微信的推送记录，看不出什么问题，已注册未推送可能跟企业微信自己的推送策略有关系
另外企业微信在MIUI上没有小米的推送吗

**Comment by zintine** [comment]
> 日志中没有企业微信的推送记录，看不出什么问题，已注册未推送可能跟企业微信自己的推送策略有关系 另外企业微信在MIUI上没有小米的推送吗

能不能特殊适配一下企业微信，京东，高德，微博这几个？

**Comment by spark-777** [comment]
> 

我用的不是miui，刷了类原生才想自己弄一个推送

**Comment by fei-ke** [comment]
> > 日志中没有企业微信的推送记录，看不出什么问题，已注册未推送可能跟企业微信自己的推送策略有关系 另外企业微信在MIUI上没有小米的推送吗
> 
> 能不能特殊适配一下企业微信，京东，高德，微博这几个？

你说的这几个都能正常注册，无需特殊适配

**Comment by zintine** [comment]
> > > 日志中没有企业微信的推送记录，看不出什么问题，已注册未推送可能跟企业微信自己的推送策略有关系 另外企业微信在MIUI上没有小米的推送吗
> > 
> > 
> > 能不能特殊适配一下企业微信，京东，高德，微博这几个？
> 
> 你说的这几个都能正常注册，无需特殊适配

我的意思是这几个能不能特殊适配一下lspatch啊，这些要么不注册要么不推

**Comment by fei-ke** [comment]
@zintine 企业微信试一下这个版本 https://github.com/fei-ke/HMSPush/suites/9408426444/artifacts/444180565

**Comment by zintine** [comment]
> @zintine 企业微信试一下这个版本 https://github.com/fei-ke/HMSPush/suites/9408426444/artifacts/444180565

这版企业微信可以注册，但不推送消息。现在的情况是：企业微信、京东、高德、微博都可以注册，但都不推送消息。
