### ISSUE TITLE
hmspush和hmscore经常睡死不推

### ISSUE THREAD

**Issue by zintine** [fei-ke/HMSPush#43]
最近总是出现忽然就不推送的现象，但一打开hmspush，先是卡一下，然后就一大堆消息都弹出来了。hmscore、hmspush、lspatch都已设置为电池不受限、自启动、锁后台，但仍然不是很管用，之前偶尔有这现象，但最近越来越频繁了。而且打开hmspush时是空白页面需要重启hmscore才恢复注册信息的次数也越来越多了。
（hmscore：6.8.0.332，hmspush：0.23，安卓13）

**Comment by fei-ke** [comment]
请保持 HMS Core 再后台运行
