### ISSUE TITLE
银行勾选了，都打不开

### ISSUE THREAD

**Issue by ballyhuang** [fei-ke/HMSPush#47]
我的手机系统是安卓13，hmspush是最新版的，在LSPosed里各家银行都勾选后，变成秒退了！

**Comment by duzhaokun123** [comment]
银行反 xposed 不是很正常

你在期待 hmspush 提供反反 xposed 吗

**Comment by fei-ke** [comment]
无日志，无有效信息，无法帮你查看问题，不过还是建议你把 LSPosed 升级到最新的 CI 版本试一下
