### ISSUE TITLE
一些支持HMS的应用重启多次还无法成功注册

### ISSUE THREAD

**Issue by DsTansice** [fei-ke/HMSPush#48]
**描述问题**
在此描述你的问题
百度贴吧、快手、快手极速版、中国联通、抖音极速版、抖音火山版、皮皮虾、堆糖
这些应用重启多次仍无法注册hms

**运行环境**
比如 LSPosed / LSPatch 
lsposed
**LSPosed 版本**
1.8.5

**HMS Core 版本**
最新

**HMS Push 版本**
最新

**问题应用版本**

百度贴吧、快手、快手极速版、中国联通、抖音极速版、抖音火山版、皮皮虾、堆糖
均为华为应用市场最新版本

**问题应用下载渠道**
华为应用市场

**LSPosed 日志**

**Comment by fei-ke** [comment]
日志呢
