### ISSUE TITLE
消息叠加(保留历史消息)，只通知第一条消息

### ISSUE THREAD

**Issue by Herman-Xu** [fei-ke/HMSPush#50]
**描述问题**
QQ开启保留历史消息功能后，同一个会话的消息会叠加，但是顶部横幅通知一直通知第一条消息，不通知最新消息，建议改为通知最新消息

**运行环境**
LSPosed 

**LSPosed 版本**
1.8.6(6713)

**HMS Core 版本**
6.9.0.302

**HMS Push 版本**
0.0.25(175)

**问题应用版本**
QQ 8.9.28

**问题应用下载渠道**
官网

**LSPosed 日志**

**Comment by fei-ke** [comment]
什么设备，发一下日志和截图

**Comment by Herman-Xu** [comment]
> 

OPPO Reno2Z，ColorOS11，Android11

**Comment by Herman-Xu** [comment]
> 什么设备，发一下日志和截图

已加tg群反馈

**Comment by fei-ke** [comment]
经排查是 ColorOS 简洁通知的原因，未正确取通知内容，请向 OPPO 反馈
