### ISSUE TITLE
HMS Core一直是未注册状态

### ISSUE THREAD

**Issue by skinnyshy** [fei-ke/HMSPush#54]
**描述问题**
HMS一直显示未注册

**运行环境**
LSPosed / LSPatch 
LineageOS 20-20230302

**LSPosed 版本**
1.8.6（6172）-Zygisk

**HMS Core 版本**
6.9.6.302

**HMS Push 版本**
0.0.25

**问题应用版本**
0.0.25

**问题应用下载渠道**
github

**LSPosed 日志**
[LSPosed_2023-03-03T08_40_15.091713.zip](https://github.com/fei-ke/HMSPush/files/10877518/LSPosed_2023-03-03T08_40_15.091713.zip)
![Screenshot_20230303-084058_HMSPush](https://user-images.githubusercontent.com/12553514/222614112-e32db6e9-840c-46ed-9473-714668ccd107.png)
![Screenshot_20230303-084111_Magisk](https://user-images.githubusercontent.com/12553514/222614123-b93a837c-b7b1-4812-b8ab-df97fcad941c.png)
![Screenshot_20230303-084126_Shell](https://user-images.githubusercontent.com/12553514/222614126-83fd557b-ba29-47f5-81fd-557c956382b3.png)

**Comment by fei-ke** [comment]
重启 HMS Core 重试，尝试清除 HMS Core 数据

**Comment by skinnyshy** [comment]
更新了下LineageOS，注册时候科学上网关闭，可以了，谢谢开发者
