### ISSUE TITLE
支持华为推送却无法注册

### ISSUE THREAD

**Issue by om2mo** [fei-ke/HMSPush#58]
腾讯手游加速器，这个应用支持华为推送但是始终无法注册，不知道怎么回事。

![SmartSelect_20230417_193719_One UI Home](https://user-images.githubusercontent.com/4419299/232473377-61b7be7c-7045-48f6-acd6-bdf2b3d1af97.jpg)

![SmartSelect_20230417_193416_LibChecker](https://user-images.githubusercontent.com/4419299/232473016-69d418d1-2cac-4d46-a088-c4c76eb97a50.jpg)

**Comment by notxx** [comment]
我的经验是，把Proxy的华为推送服务禁用掉，就有比较高概率让原生的华为推送服务激活，进而注册到HMSPush

**Comment by om2mo** [comment]
> 我的经验是，把Proxy的华为推送服务禁用掉，就有比较高概率让原生的华为推送服务激活，进而注册到HMSPush

怎么禁用的

**Comment by notxx** [comment]
> 怎么禁用的

用灭霸（Thanox），其他的禁用服务的工具应该也行的
