### ISSUE TITLE
王者荣耀注册后无法开启高帧率

### ISSUE THREAD

**Issue by om2mo** [fei-ke/HMSPush#61]
开启注册后只有60帧，取消取消注册才有高帧率选项。

**Comment by notxx** [comment]
这是华为和王者荣耀这边有协议吧

**Comment by fei-ke** [comment]
因为设备伪装导致机型改变，特殊适配了一下，可以试下这个包: https://github.com/fei-ke/HMSPush/actions/runs/5032513906
另外对游戏启用 hook 容易被封号，请慎重使用
