### ISSUE TITLE
使用QQ进行推送测试成功，但是消息会被快速清理

### ISSUE THREAD

**Issue by sdecoder** [fei-ke/HMSPush#62]
**描述问题**
如题所述：
1. 环境配置和应用设置一切正常。
2. 使用QQ进行推送测试，一切正常；
3. 但是QQ收到的消息如果故意放置不管的话，3-5分钟内会自动消失；
4. 这对于用户来说是不可接受的，大部分用户不希望因为3-5分钟没有看手机就错过了重要消息；

**运行环境**
比如 LSPosed / LSPatch 

**LSPosed 版本**
>比如 1.8.5(6695)，请提供详细版本号，不要使用`最新`等词汇，下同
LSPosed版本=1.8.6（6712）-Zygisk

**HMS Core 版本**
6.11.0.302（61100302）下载来自应用宝

**HMS Push 版本**
0.0.26（185）
来自https://github.com/fei-ke/HMSPush/releases/tag/v0.0.26

**问题应用版本**
QQ：安卓版8.9.58.11175

**问题应用下载渠道**
QQ下载来自应用宝

**LSPosed 日志**
[LSPosed_2023-06-26T23_52_27.860134.zip](https://github.com/fei-ke/HMSPush/files/11871264/LSPosed_2023-06-26T23_52_27.860134.zip)

**Comment by sdecoder** [comment]
> 根据其他用户的反馈，黑阈会导致这个情况，或许是黑阈通过通知判定应用在后台自启了，但是应用实际并没有在运行，可向黑域反馈看看。

好的，谢谢提醒。我这边稍微补充几点信息：
1. 我确实有使用黑阈；
2. 不过黑阈中我把HMS Core和HMS Push均做了忽略处理；
3. 请问是否可以推荐替代黑阈的类似软件？我这边对HMS推送有强需求，为此可以放弃黑阈；

**Comment by notxx** [comment]
> 2. 请问是否可以推荐替代黑阈的类似软件？我这边对HMS推送有强需求，为此可以放弃黑阈；

推荐灭霸（Thanox），用它的冻结，不清除通知
