### ISSUE TITLE
拼多多商家版无法注册

### ISSUE THREAD

**Issue by JamesLiu0802** [fei-ke/HMSPush#63]
**描述问题**
拼多多商家版无法注册

**运行环境**
LSPosed

**LSPosed 版本**
1.8.6(6712)

**HMS Core 版本**
6.11.0.332

**HMS Push 版本**
0.0.26-14-g37c36a1

**问题应用版本**
拼多多商家版5.9.1

**问题应用下载渠道**
华为应用商店

**LSPosed 日志**
----part 2 start----
[ 2023-08-19T13:46:38.355        0:   791:  1173 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2023-08-19T13:46:38.354813.log
[ 2023-08-19T13:46:44.337        0:   791:  1074 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2023-08-19T13:46:44.339        0:   791:  1173 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2023-08-19T13:46:44.338995.log
[ 2023-08-19T13:48:40.112        0:   791: 14938 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 136)
[ 2023-08-19T13:48:40.151    10478: 19881: 19881 I/LSPosed         ] Loading xposed for com.huawei.hwid.container3/10478
[ 2023-08-19T13:48:40.161    10478: 19881: 19881 I/LSPosed-Bridge  ] Loading module one.yufz.hmspush from /data/app/~~e3L9HPT20RqBGiFOMPnX0Q==/one.yufz.hmspush-OJwG52tsFBWj6lJlSll6bQ==/base.apk
[ 2023-08-19T13:48:40.207    10478: 19881: 19881 I/LSPosed-Bridge  ]   Loading class one.yufz.hmspush.hook.XposedMod
[ 2023-08-19T13:48:40.416    10478: 19881: 19881 I/LSPosed-Bridge  ] [HMSPush]  XposedMod  Loaded app: com.huawei.hwid process:com.huawei.hwid.container3
[ 2023-08-19T13:48:40.509        0:   791:  1023 I/lspd            ] Background young concurrent copying GC freed 467104(23MB) AllocSpace objects, 0(0B) LOS objects, 40% free, 19MB/32MB, paused 41us,38us total 124.502ms
[ 2023-08-19T13:48:51.281        0:   791: 19900 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 148)
[ 2023-08-19T13:48:51.314        0:   791: 14941 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 160)
[ 2023-08-19T13:48:58.151    10479: 20581: 20581 I/LSPosed         ] Loading xposed for one.yufz.hmspush/10479
[ 2023-08-19T13:48:58.155    10479: 20581: 20581 I/LSPosed-Bridge  ] Loading module one.yufz.hmspush from /data/app/~~e3L9HPT20RqBGiFOMPnX0Q==/one.yufz.hmspush-OJwG52tsFBWj6lJlSll6bQ==/base.apk
[ 2023-08-19T13:48:58.165    10479: 20581: 20581 I/LSPosed-Bridge  ]   Loading class one.yufz.hmspush.hook.XposedMod
[ 2023-08-19T13:48:58.239    10479: 20581: 20581 W/LSPosed         ] New modules detected, hook preferences
[ 2023-08-19T13:48:58.243    10479: 20581: 20581 I/LSPosed-Bridge  ] [HMSPush]  XposedMod  Loaded app: one.yufz.hmspush process:one.yufz.hmspush
[ 2023-08-19T13:48:58.249    10479: 20581: 20581 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  fake() called with: packageName = one.yufz.hmspush, processName = one.yufz.hmspush
[ 2023-08-19T13:48:58.249    10479: 20581: 20581 I/LSPosed-Bridge  ] [HMSPush]  Common  fake() called with: packageName = one.yufz.hmspush
[ 2023-08-19T13:48:58.261    10479: 20581: 20581 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  one.yufz.hmspush.app.App@8b8b12b.attachBaseContext() called
[ 2023-08-19T13:48:58.264    10478:  3687:  3720 I/LSPosed-Bridge  ] [HMSPush]  BridgeContentProvider  query() called with: uri = content://com.huawei.hms/hmspush/disableSignature, projection = null, selection = null, selectionArgs = null, sortOrder = null
[ 2023-08-19T13:48:58.265    10479: 20581: 20581 I/LSPosed-Bridge  ] [HMSPush]  HookHmsDeviceId  hook() called with: processName = one.yufz.hmspush
[ 2023-08-19T13:48:58.361    10478:  3687:  3720 I/LSPosed-Bridge  ] [HMSPush]  BridgeContentProvider  query() called with: uri = content://com.huawei.hms/hmspush/service, projection = null, selection = null, selectionArgs = null, sortOrder = null
[ 2023-08-19T13:49:47.573    10487: 21003: 21003 I/LSPosed         ] Loading xposed for com.xunmeng.merchant/10487
[ 2023-08-19T13:49:47.576    10487: 21003: 21003 I/LSPosed-Bridge  ] Loading module one.yufz.hmspush from /data/app/~~e3L9HPT20RqBGiFOMPnX0Q==/one.yufz.hmspush-OJwG52tsFBWj6lJlSll6bQ==/base.apk
[ 2023-08-19T13:49:47.586    10487: 21003: 21003 I/LSPosed-Bridge  ]   Loading class one.yufz.hmspush.hook.XposedMod
[ 2023-08-19T13:49:47.635    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  XposedMod  Loaded app: com.xunmeng.merchant process:com.xunmeng.merchant
[ 2023-08-19T13:49:47.640    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  fake() called with: packageName = com.xunmeng.merchant, processName = com.xunmeng.merchant
[ 2023-08-19T13:49:47.641    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  Common  fake() called with: packageName = com.xunmeng.merchant
[ 2023-08-19T13:49:47.656    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  com.xunmeng.merchant.app.PDDApplication@201cda5.attachBaseContext() called
[ 2023-08-19T13:49:47.658    10478:  3687:  3717 I/LSPosed-Bridge  ] [HMSPush]  BridgeContentProvider  query() called with: uri = content://com.huawei.hms/hmspush/disableSignature, projection = null, selection = null, selectionArgs = null, sortOrder = null
[ 2023-08-19T13:49:47.659    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  HookHmsDeviceId  hook() called with: processName = com.xunmeng.merchant
[ 2023-08-19T13:49:49.061    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.miui.ui.version.name
[ 2023-08-19T13:49:49.080    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.build.version.emui
[ 2023-08-19T13:49:49.107    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.miui.ui.version.name
[ 2023-08-19T13:49:49.245    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.miui.ui.version.name
[ 2023-08-19T13:49:49.250    10487: 21003: 21114 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.miui.ui.version.name
[ 2023-08-19T13:49:49.257    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.build.version.emui
[ 2023-08-19T13:49:49.260    10487: 21003: 21114 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.build.version.emui
[ 2023-08-19T13:49:49.305    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  XposedMod  Loaded app: com.google.android.webview process:com.xunmeng.merchant
[ 2023-08-19T13:49:49.305    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  fake() called with: packageName = com.google.android.webview, processName = com.xunmeng.merchant
[ 2023-08-19T13:49:49.305    10487: 21003: 21003 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  fake() called, ignore com.google.android.webview
[ 2023-08-19T13:49:49.603    10487: 21306: 21306 I/LSPosed         ] Loading xposed for com.xunmeng.merchant:pushservice/10487
[ 2023-08-19T13:49:49.609    10487: 21306: 21306 I/LSPosed-Bridge  ] Loading module one.yufz.hmspush from /data/app/~~e3L9HPT20RqBGiFOMPnX0Q==/one.yufz.hmspush-OJwG52tsFBWj6lJlSll6bQ==/base.apk
[ 2023-08-19T13:49:49.644    10487: 21306: 21306 I/LSPosed-Bridge  ]   Loading class one.yufz.hmspush.hook.XposedMod
[ 2023-08-19T13:49:49.776    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  XposedMod  Loaded app: com.xunmeng.merchant process:com.xunmeng.merchant:pushservice
[ 2023-08-19T13:49:49.782    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  fake() called with: packageName = com.xunmeng.merchant, processName = com.xunmeng.merchant:pushservice
[ 2023-08-19T13:49:49.782    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  Common  fake() called with: packageName = com.xunmeng.merchant
[ 2023-08-19T13:49:49.796    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  FakeDevice  com.xunmeng.merchant.app.PDDApplication@201cda5.attachBaseContext() called
[ 2023-08-19T13:49:49.798    10478:  3687:  3717 I/LSPosed-Bridge  ] [HMSPush]  BridgeContentProvider  query() called with: uri = content://com.huawei.hms/hmspush/disableSignature, projection = null, selection = null, selectionArgs = null, sortOrder = null
[ 2023-08-19T13:49:49.798    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  HookHmsDeviceId  hook() called with: processName = com.xunmeng.merchant:pushservice
[ 2023-08-19T13:49:50.009    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.miui.ui.version.name
[ 2023-08-19T13:49:50.048    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.build.version.emui
[ 2023-08-19T13:49:50.147    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.miui.ui.version.name
[ 2023-08-19T13:49:50.178    10487: 21306: 21306 I/LSPosed-Bridge  ] [HMSPush]  FakeProperties  hook getprop ro.build.version.emui

**Comment by fei-ke** [comment]
未看到相关日志，不确定商家版是否有正常集成推送服务，无商家账号无法测试。
