### ISSUE TITLE
开启模块会导致hms闪退

### ISSUE THREAD

**Issue by XMWML** [fei-ke/HMSPush#64]
**描述问题**
开启模块后
从应用市场点击头像打开hms个人信息界面会闪退
关闭模块后正常

**运行环境**
LSPosed
**LSPosed 版本**
1.8.6(6984)
**HMS Core 版本**
version 6.11.0.332
**HMS Push 版本**
version 0.0.26-13-g42e6d12
**问题应用版本**
version 6.11.0.332
**问题应用下载渠道**
华为应用市场
**LSPosed 日志**
[LSPosed_2023-08-29T20_34_13.121730.zip](https://github.com/fei-ke/HMSPush/files/12464531/LSPosed_2023-08-29T20_34_13.121730.zip)

**Comment by fei-ke** [comment]
无法复现，是否有禁用或阻止 HMS Core 相关组件
