### ISSUE TITLE
拼多多无法注册

### ISSUE THREAD

**Issue by Samuel-Shao** [fei-ke/HMSPush#65]
**描述问题**
拼多多无法注册

**运行环境**
LineageOS 20，magisk 25.2，LSPosed

**LSPosed 版本**
1.9.1（6990）

**HMS Core 版本**
6.11.0.332

**HMS Push 版本**
0.0.26

**问题应用版本**
6.76.0

**问题应用下载渠道**
华为应用市场

**LSPosed 日志**

**Comment by fei-ke** [comment]
测试正常注册，请提供日志
