### ISSUE TITLE
push需要挂后台自启？

### ISSUE THREAD

**Issue by biange200** [fei-ke/HMSPush#66]
![Screenshot_20231012_161444.jpg](https://github.com/fei-ke/HMSPush/assets/37582806/365d5fdb-018c-41b0-9bc4-621164da6c32)

![Screenshot_20231012_070335.jpg](https://github.com/fei-ke/HMSPush/assets/37582806/733df745-8825-408e-982d-fa187c92f5f9)

[]()![正在上传 Screenshot_20231012_070155.jpg…]()

![Screenshot_20231011_120736.jpg](https://github.com/fei-ke/HMSPush/assets/37582806/1a8373c5-ad4e-495a-9254-52bc1fb72c59)

问下，hmspush和core都需要开自启，电池不优化？push没有开机自启权限，
还有个问题是cherrygram有个huawei版本，可以添加到hmspush的注册列表里？push也只支持国内软件？![Screenshot_20231012_193146.jpg](https://github.com/fei-ke/HMSPush/assets/37582806/49b224f4-0bae-44ad-8b2a-9d356e450dca)

**Comment by fei-ke** [comment]
HMS Core 需要保持后台+电池不优化，HMSPush 不需要。
是否支持海外应用，取决于 HMS Core 的运行环境，无法同时支持海内海外应用
