### ISSUE TITLE
应用名称的颜色可不可以做成和自定义图标一样的颜色？

### ISSUE THREAD

**Issue by zintine** [fei-ke/HMSPush#69]
**描述问题**
在此描述你的问题

**运行环境**
比如 LSPosed / LSPatch 

**LSPosed 版本**
>比如 1.8.5(6695)，请提供详细版本号，不要使用`最新`等词汇，下同

**HMS Core 版本**

**HMS Push 版本**

**问题应用版本**

**问题应用下载渠道**

**LSPosed 日志**

**Comment by zintine** [comment]
可能我描述的不太准确，意思就是应用名称的颜色跟随应用图标的颜色，现在就都只是黑色的。

**Comment by fei-ke** [comment]
不可以，系统未提供此类接口
