### ISSUE TITLE
无法激活模块

### ISSUE THREAD

**Issue by RoundedKnot4342** [fei-ke/HMSPush#71]
描述问题
勾选了HMS Core后强行停止了HMS Core依然显示未激活

运行环境
LSPosed

LSPosed 版本
1.9.1(6990)

HMS Core 版本
6.12.2.302(61202302)

HMS Push 版本
0.0.26(185)

[LSPosed_2023-11-04T15_47_04.456229.zip](https://github.com/fei-ke/HMSPush/files/13256091/LSPosed_2023-11-04T15_47_04.456229.zip)

**Comment by RoundedKnot4342** [comment]
设备系统为ColorOS 13.1 Android13

**Comment by fei-ke** [comment]
HMS Core 未在后台运行

**Comment by RoundedKnot4342** [comment]
> HMS Core未在后台运行

我确定HMS Core处于后台运行状态，不过也许是ColorOS13的问题，我之前的ColorOS7.1没有任何问题

**Comment by fei-ke** [comment]
日志中没有 HMS Core 运行的日志，请给 HMS Core 自启权限和后台运行的权限
```
OplusAppStartupManager: prevent start com.huawei.hwid, cmp ComponentInfo{com.huawei.hwid/com.huawei.hms.dynamic.module.manager.query.ModuleQueryProvider} by contentprovider one.yufz.hmspush callingUid 10121
```
