### ISSUE TITLE
Android 13系统内Core闪退

### ISSUE THREAD

**Issue by zyh941** [fei-ke/HMSPush#8]
开发者您好，我前几天刚装了HMSPush并成功使用了它实现了腾讯TIM、支付宝Alipay和云闪付的0后台推送。当时我在用Android 12L 202207月更新的系统，附件是当时成功的截图。不过我昨天更新了新鲜的Android 13正式版，然后HMS Core这个app就经常闪退了，提示应用已停止运行。我重装了几次HMS Core也重启过手机，都是显示HMS Core闪退。请帮看看是什么原因，需要我提供什么？
手机型号：Pixel 5，Android 13正式版，HMS Core软件版本：6.6.0.330，HMSPush模块版本：0.0.10
![HMS](https://user-images.githubusercontent.com/95530307/185272140-127342a2-9c68-49e3-b090-c5c92e84e21f.png)

**Comment by fei-ke** [comment]
HMS Core  在 Android 13 上闪退，请向华为反馈

**Comment by zyh941** [comment]
好的，我没有华为账号，并且没有用过它的产品，等其他用户向华为反馈。

**Comment by fei-ke** [comment]
https://github.com/fei-ke/HMSPush/releases/tag/v0.0.11
