### ISSUE TITLE
支持安卓8.0的原生通知渠道(即channel，隔壁MiPush实现了)

### ISSUE THREAD

**Issue by Resurrection2981** [fei-ke/HMSPush#91]
**描述问题**
当前所有通知都是一个Channel，比如飞书的是 “飞书[HMS]普通通知”，如图。![Screenshot_20240709-184853](https://github.com/fei-ke/HMSPush/assets/45873933/166212a4-3043-4309-b866-ccfc63205544)
原来用MiPush的时候可以分别设置“@我”和“群聊”等的铃声，改成和原应用声音一致(系统自带push都是这个效果）。后来飞书检测更严格了，MiPush无法注册，遂转HMSPush。Channel只有一个，便设置成飞书普通消息的铃声在用。
后面换了手机是Moto的MyUI 4.0，Android12，更难受的事情发生了，这个“飞书[HMS]普通通知”的 Channel 每次改完飞书普通消息的声音，下次推送就会被改回系统通知铃声，导致现在无法区分是“系统通知”还是“工作消息”，但这个可能是myui的兼容问题。
总之，希望HMSPush能完整支持原生安卓8.0+的通知渠道，实现自定义不同的消息声音。

**运行环境**
LSPosed

**LSPosed 版本**
1.9.2(7024)

**HMS Core 版本**
6.13.0.322

**HMS Push 版本**
0.0.27-4-ga53d7a8

**问题应用版本**
7.19.6

**问题应用下载渠道**
飞书官方，华为商店都有试过
https://www.feishu.cn/download

**LSPosed 日志**
[LSPosed_2024-07-09T18_58_56.148336.zip](https://github.com/user-attachments/files/16142340/LSPosed_2024-07-09T18_58_56.148336.zip)

**Comment by fei-ke** [comment]
HMS 官方默认只给了三个推送 channel，官方根据应用类型，消息内容自动划分，大部分应用也没有再单独申请自分类权限，除非应用自己划分更多 channel，插件也没办法处理，参考 [消息分类标准]。(https://developer.huawei.com/consumer/cn/doc/HMSCore-Guides/message-classification-0000001149358835)

手动更改铃声后被恢复应该是部分系统上的 bug，可以看一下有没有解决办法。

**Comment by Resurrection2981** [comment]
同时还发现了 HMSPush 的消息没法同步到我 WearOS 4 的 Pixel Watch 2 上，不确定是不是也是系统 BUG，我这几天刷个系统看看。
